//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TocoDo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TocoDo.Properties.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9737d654-4116-4840-9090-5869b7a77c59.
        /// </summary>
        public static string AppCenterAndroidSecret {
            get {
                return ResourceManager.GetString("AppCenterAndroidSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37adddfa-9b95-48e0-85c9-a6f76f581981.
        /// </summary>
        public static string AppCenterIosSecret {
            get {
                return ResourceManager.GetString("AppCenterIosSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uwp={0};android={1};ios={2}.
        /// </summary>
        public static string AppCenterMessage {
            get {
                return ResourceManager.GetString("AppCenterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51afeb7a-13f7-4026-9738-584b0608bd90.
        /// </summary>
        public static string AppCenterUwpSecret {
            get {
                return ResourceManager.GetString("AppCenterUwpSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQLite.db3.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
    }
}
